apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "storage-claim-log"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "100Mi"
  volumeName: "pv0001"
